ALERGENS = [
    {
        id: 0
    },
    {
        id: 1,
        nom_ca: "Cereals que contenen gluten",
        nom_es: "Cereales que contienen gluten",
        nom_en: "Cereals containing gluten",
        nom_fr: "Céréales contenant du gluten",
        subNom_ca: "Cereals que contenen gluten: blat, ordi sègol, civada, espelta, kamut",
        subNom_es: "Cereales que contienen gluten: trigo, cebada, centeno, espelta, kamut",
        subNom_en: "Cereals containing gluten: wheat, barley, rye, spelt, kamut",
        subNom_fr: "Céréales contenant du gluten : blé, orge, seigle, épeautre, kamut",
        descripcio_ca: "<div class='alergens'><p>El gluten és una proteïna que es troba en el blat, ordi, sègol, civada, espelta, kamut i varietats híbrides i productes derivats d’aquests cereals.</p><p><strong>Al·lèrgia als cereals</strong>: Els cereals també poden causar al·lèrgies alimentàries, encara que no són comunes en la població. Els al·lèrgens dels cereals poden reaccionar de forma encreuada amb els al·lèrgens del pol·len.</p></div>",
        descripcio_es: "<div class='alergens'><p>El gluten es una proteína que se encuentra en el trigo, cebada, centeno, avena, espelta, kamut y variedades híbridas y productos derivados de estos cereales.</p><p><p><strong>Alergia a los cereales</strong>: Los cereales también pueden causar alergias alimentarias, aunque no son comunes en la población. Los alérgenos de los cereales pueden reaccionar de forma cruzada con los alérgenos del polen.</p></div>",
        descripcio_en: "<div class='alergens'><p>Gluten is a protein found in wheat, barley, rye, oats, spelt, kamut and hybrid varieties and products derived from these cereals.</p><p>Cereals can also cause food allergies, although they are not common in the population. Cereal allergens can cross-react with pollen allergens.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Le gluten est une protéine présente dans le blé, l'orge, le seigle, l'avoine, l'épeautre, le kamut et les variétés hybrides, ainsi que dans les produits dérivés de ces céréales.</p><p><strong>Allergie aux céréales</strong> : Les céréales peuvent également provoquer des allergies alimentaires, bien qu'elles ne soient pas courantes. Les allergènes céréaliers peuvent réagir de manière croisée avec les allergènes polliniques.</p></div>",
        imatge: "al-1.png"
    },
    {
        id: 2,
        nom_ca: "Crustacis i productes amb crustacis",
        nom_es: "Crustáceos y productos con crustáceos",
        nom_en: "Crustaceans and products with crustaceans",
        nom_fr: "Crustacés et produits à base de crustacés",
        subNom_ca: "Crustacis i productes que contenen crustacis",
        subNom_es: "Crustáceos y productos que contienen crustáceos",
        subNom_en: "Crustaceans and products containing crustaceans",
        subNom_fr: "Crustacés et produits contenant des crustacés",
        descripcio_ca: "<div class='alergens'><p>En aquest grup d’al·lèrgens s’inclouen totes les espècies de crustacis (gambes, els escamarlans, els llagostins, els crancs, la llagosta, el llamàntol, etc.). Es tracta d’una al·lèrgia força comuna i, a causa de la reactivitat encreuada entre espècies, un mateix individu pot reaccionar a diferents espècies de crustacis. A més, algunes persones poden tenir reaccions per inhalació de vapors de cocció i algunes altres també poden ser al·lèrgiques als mol·luscs.</p></div>",
        descripcio_es: "<div class='alergens'><p>Este grupo de alérgenos incluye todas las especies de crustáceos (camarones, langostinos, cangrejos, langosta, nécoras, etc.). Se trata de una alergia bastante común y, debido a la reactividad cruzada entre especies, una misma persona puede reaccionar a diferentes especies de crustáceos. Además, algunas personas pueden tener reacciones por inhalación de vapores de cocción y algunas otras también pueden ser alérgicas a los moluscos.</p></div>",
        descripcio_en: "<div class='alergens'><p>This group of allergens includes all species of crustaceans (shrimp, prawns, crabs, lobster, crayfish, etc.). It is a fairly common allergy and, due to cross-reactivity between species, the same individual can react to different species of crustaceans. In addition, some people may have reactions from inhaling cooking vapors and some others may also be allergic to mollusks.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Ce groupe d'allergènes comprend toutes les espèces de crustacés (crevettes, langoustines, crabes, langoustes, homards, etc.). C'est une allergie assez courante et, en raison de la réactivité croisée entre les espèces, une même personne peut réagir à différentes espèces de crustacés. De plus, certaines personnes peuvent avoir des réactions en inhalant des vapeurs de cuisson et certaines autres peuvent également être allergiques aux mollusques.</p></div>",
        imatge: "al-2.png"
    },
    {
        id: 3,
        nom_ca: "Ous i productes derivats",
        nom_es: "Huevos y productos derivados",
        nom_en: "Eggs and egg products",
        nom_fr: "Œufs et produits dérivés",
        subNom_ca: "Ous i productes que contenen ou",
        subNom_es: "Huevos y productos que contienen huevo",
        subNom_en: "Eggs and products containing eggs",
        subNom_fr: "Oeufs et produits contenant des œufs",
        descripcio_ca: "<div class='alergens'><p>Es pot trobar als productes de pastisseria, pasta, plats preparats, productes carnis, salses, condiments, caramels, flams, gelats, alguns formatges, sopes...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se puede encontrar en productos de pastelería, pasta, platos preparados, productos cárnicos, salsas, condimentos, caramelos, flanes, helados, algunos quesos, sopas...</p></div>",
        descripcio_en: "<div class='alergens'><p>It can be found in bakery products, pasta, prepared dishes, meat products, sauces, condiments, candies, custards, ice creams, some cheeses, soups...</p></div>",
        descripcio_fr: "<div class='alergens'><p>On peut en trouver dans les produits de boulangerie, les pâtes, les plats préparés, les produits carnés, les sauces, les condiments, les bonbons, les flans, les crèmes glacées, certains fromages, les soupes...</p></div>",
        imatge: "al-3.png"
    },
    {
        id: 4,
        nom_ca: "Peix i productes amb peix",
        nom_es: "Pescado y productos con pescado",
        nom_en: "Fish and fish products",
        nom_fr: "Poissons et produits à base de poisson",
        subNom_ca: "Peix i productes que contenen peix",
        subNom_es: "Pescado y productos que contienen pescado",
        subNom_en: "Fish and products containing fish",
        subNom_fr: "Poisson et produits contenant du poisson",
        descripcio_ca: "<div class='alergens'><p>Es considera al·lergen qualsevol espècie de peix ja que la majoria d'espècies poden presentar reactivitat encreuada entre si, i per tant cap no es pot considerar segura per a una persona al·lèrgica.</p></div>",
        descripcio_es: "<div class='alergens'><p>Se considera alérgeno cualquier especie de pescado ya que la mayoría de especies pueden presentar reactividad cruzada entre sí, y por tanto ninguna se puede considerar segura para una persona alérgica.</p></div>",
        descripcio_en: "<div class='alergens'><p>Any species of fish is considered an allergen since most species can present cross-reactivity between them, and therefore none can be considered safe for an allergic person.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Toute espèce de poisson est considérée comme un allergène car la plupart des espèces peuvent présenter une réactivité croisée entre elles, et donc aucune ne peut être considérée comme sûre pour une personne allergique.</p></div>",
        imatge: "al-4.png"
    },
    {
        id: 5,
        nom_ca: "Cacauets i derivats",
        nom_es: "Cacahuetes y derivados",
        nom_en: "Peanuts and derivatives",
        nom_fr: "Arachides et dérivés",
        subNom_ca: "Cacauet i productes que contenen cacauet",
        subNom_es: "Cacahuete y productos que contienen cacahuetes",
        subNom_en: "Peanuts and products containing peanuts",
        subNom_fr: "Arachide et produits contenant des arachides",
        descripcio_ca: "<div class='alergens'><p>Pertanyen a la família de les lleguminoses i són els causants principals d’anafilaxi i els que provoquen reaccions al·lèrgiques més greus. És habitual que les persones al·lèrgiques al cacauet també reaccionin a la fruita seca i a altres membres de la família de les lleguminoses tals com la soja o el tramús. Els tractaments de calor augmenten l’efecte al·lergogen del cacauet.</p></div>",
        descripcio_es: "<div class='alergens'><p>Pertenecen a la familia de las leguminosas y son los causantes principales de anafilaxia y de las reacciones alérgicas más graves. Es habitual que las personas alérgicas al cacahuete también reaccionen a la fruta seca y a otros miembros de la familia de las leguminosas como la soja o el altramuz. Los tratamientos de calor aumentan el efecto alergénico del cacahuete.</p></div>",
        descripcio_en: "<div class='alergens'><p>Belonging to the family of legumes, peanuts are the main cause of anaphylaxis and the most severe allergic reactions. It is common for people allergic to peanuts to also react to tree nuts and other members of the legume family such as soy or lupin. Heat treatments increase the allergenic effect of peanuts.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Appartenant à la famille des légumineuses, les cacahuètes sont la principale cause d’anaphylaxie et des réactions allergiques les plus graves. Il est courant que les personnes allergiques aux cacahuètes réagissent également aux fruits à coque et à d'autres membres de la famille des légumineuses tels que le soja ou le lupin. Les traitements thermiques augmentent l'effet allergène des cacahuètes.</p></div>",
        imatge: "al-5.png"
    },
    {
        id: 6,
        nom_ca: "Soja i productes amb soja",
        nom_es: "Soja y productos con soja",
        nom_en: "Soy and soy products",
        nom_fr: "Soja et produits à base de soja",
        subNom_ca: "Soja i productes que contenen soja",
        subNom_es: "Soja y productos que contienen soja",
        subNom_en: "Soybeans and products containing soybeans",
        subNom_fr: "Soja et produits contenant du soja",
        descripcio_ca: "<div class='alergens'><p>A més de la salsa de soja, podem trobar-ne en alguns productes, com ara, a altres tipus de salses, condiments, a les postres, als gelats i als productes carnis; productes derivats de la soja com aïllats de proteïna de soja, els concentrats de proteïna de soja i la lecitina de soja que es fan servir com a  ingredients en nombrosos plats i també a la xocolata. Són derivats de la soja el tofu, el miso i el tempeh.</p></div>",
        descripcio_es: "<div class='alergens'><p>Además de la salsa de soja, podemos encontrarla en algunos productos, como en otros tipos de salsas, condimentos, en los postres, en los helados y en los productos cárnicos; productos derivados de la soja como aislados de proteína de soja, los concentrados de proteína de soja y la lecitina de soja que se utilizan como ingredientes en numerosos platos y también en el chocolate. Son derivados de la soja el tofu, el miso y el tempeh.</p></div>",
        descripcio_en: "<div class='alergens'><p>In addition to soy sauce, it can be found in some products, such as other types of sauces, condiments, desserts, ice creams, and meat products; soy derivatives such as soy protein isolates, soy protein concentrates, and soy lecithin are used as ingredients in numerous dishes and also in chocolate. Soy products include tofu, miso, and tempeh.</p></div>",
        descripcio_fr: "<div class='alergens'><p>En plus de dans la sauce soja, on peut trouver du soja dans certains produits, comme d'autres types de sauces, condiments, desserts, glaces et produits carnés ; produits dérivés du soja tels que les isolats de protéines de soja, les concentrés de protéines de soja et la lécithine de soja qui sont utilisés comme ingrédients dans de nombreux plats ainsi que dans le chocolat. Le tofu, le miso et le tempeh sont dérivés du soja.</p></div>",
        imatge: "al-6.png"
    },
    {
        id: 7,
        nom_ca: "Llet i derivats, inclosa la lactosa",
        nom_es: "Leche y derivados, incluida la lactosa",
        nom_en: "Milk and dairy products, including lactose",
        nom_fr: "Lait et produits laitiers, y compris le lactose",
        subNom_ca: "Llet i els seus derivats (inclosa la lactosa)",
        subNom_es: "Leche y sus derivados (incluida la lactosa)",
        subNom_en: "Milk and its derivatives (including lactose)",
        subNom_fr: "Lait et ses dérivés (y compris le lactose)",
        descripcio_ca: "<div class='alergens'><p>Inclou, entre d’altres, la llet de vaca, cabra, ovella i búfala. A més, també s’hi inclouen els productes làctics, com ara la mantega, el formatge, els iogurts, la crema de llet, els flams, les natilles, els gelats... Es pot trobar en una àmplia varietat d’aliments: postres, embotits, salses, pans, xocolates, croquetes, sopes...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se incluye, entre otros, la leche de vaca, cabra, oveja y búfala. Además, también se incluyen los productos lácteos, como la mantequilla, el queso, los yogures, la crema de leche, los flanes, las natillas, los helados... Se puede encontrar en una amplia variedad de alimentos: postres, embutidos, salsas, panes, chocolates, croquetas, sopas...</p></div>",
        descripcio_en: "<div class='alergens'><p>It includes, among others, cow's, goat's, sheep's and buffalo's milk. In addition, dairy products such as butter, cheese, yoghurts, milk cream, custards, creams, ice creams, etc. are also included. It can be found in a wide variety of foods: desserts, sausages, sauces, breads, chocolates, croquettes, soups...</p></div>",
        descripcio_fr: "<div class='alergens'><p>Cela comprend, entre autres, le lait de vache, de chèvre, de mouton et de buffle. En outre, les produits laitiers tels que le beurre, le fromage, les yaourts, la crème, les flans, les crèmes dessert, les glaces, etc., y sont également inclus. On peut en trouver dans une large variété d’aliments : desserts, charcuterie, sauces, pains, chocolats, croquettes, soupes...</p></div>",
        imatge: "al-7.png"
    },
    {
        id: 8,
        nom_ca: "Fruits secs i derivats",
        nom_es: "Frutos secos y derivados",
        nom_en: "Nuts and derivatives",
        nom_fr: "Fruits secs et dérivés",
        subNom_ca: "Fruita seca de clofolla: ametlles, avellanes, nous, anacards, pacanes, nous del Brasil, festucs, macadàmies i nous d’Austràlia.",
        subNom_es: "Frutos secos de cáscara: almendras, avellanas, nueces, anacardos, pacanas, nueces de Brasil, pistachos, macadamias y nueces de Australia.",
        subNom_en: "Tree nuts: almonds, hazelnuts, walnuts, cashews, pecans, Brazil nuts, pistachios, macadamia nuts, and Australian nuts.",
        subNom_fr: "Fruits à coque : amandes, noisettes, noix, noix de cajou, pacanes, noix du Brésil, pistaches, noix de macadamia et noix d'Australie.",
        descripcio_ca: "<div class='alergens'><p>En aquest grup d’al·lèrgens s’inclouen les ametlles (Amygdalus communis L.), avellanes (Corylus avellana), nous (Juglans regia), anacards (Anacardium occidentale), pacanes [Carya illinoiesis (Wangenh.) K. Koch], nous del Brasil (Bertholletia excelsa), festucs (Pistacia vera), macadàmies i nous d’Austràlia (Macadamia ternifolia) i els productes derivats.</p></div>",
        descripcio_es: "<div class='alergens'><p>Este grupo de alérgenos incluye las almendras (Amygdalus communis L.), avellanas (Corylus avellana), nueces (Juglans regia), anacardos (Anacardium occidentale), pacanas [Carya illinoiesis (Wangenh.) K. Koch], nueces de Brasil (Bertholletia excelsa), pistachos (Pistacia vera), macadamias y nueces de Australia (Macadamia ternifolia) y sus productos derivados.</p></div>",
        descripcio_en: "<div class='alergens'><p>This group of allergens includes almonds (Amygdalus communis L.), hazelnuts (Corylus avellana), walnuts (Juglans regia), cashews (Anacardium occidentale), pecans [Carya illinoiesis (Wangenh.) K. Koch], Brazil nuts (Bertholletia excelsa), pistachios (Pistacia vera), macadamias and Australian nuts (Macadamia ternifolia) and their derived products.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Ce groupe d'allergènes comprend les amandes (Amygdalus communis L.), les noisettes (Corylus avellana), les noix (Juglans regia), les noix de cajou (Anacardium occidentale), les noix de pécan [Carya illinoiesis (Wangenh.) K. Koch], les noix du Brésil (Bertholletia excelsa), les pistaches (Pistacia vera), les noix de macadamia et les noix d'Australie (Macadamia ternifolia), ainsi que leurs produits dérivés.</p></div>",
        imatge: "al-8.png"
    },
    {
        id: 9,
        nom_ca: "Api i derivats",
        nom_es: "Apio y derivados",
        nom_en: "Celery and derivatives",
        nom_fr: "Céleri et dérivés",
        subNom_ca: "Api i productes derivats",
        subNom_es: "Apio y productos derivados",
        subNom_en: "Celery and celery products",
        subNom_fr: "Céleri et produits dérivés",
        descripcio_ca: "<div class='alergens'><p>Tant la planta com els brots de l’arrel es consideren substàncies al·lergògenes, i l’al·lèrgia se sol presentar amb més freqüència sobre el producte cru que sobre el cuinat.</p></div>",
        descripcio_es: "<div class='alergens'><p>Tanto la planta como los brotes de la raíz se consideran sustancias alergénicas, y la alergia suele presentarse con más frecuencia sobre el producto crudo que sobre el cocinado.</p></div>",
        descripcio_en: "<div class='alergens'><p>Both the plant and the root sprouts are considered allergenic substances, and allergy tends to occur more frequently on the raw product than on the cooked one.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Tant la plante que les pousses de la racine sont considérées comme des substances allergéniques, et l'allergie se produit généralement plus fréquemment sur le produit cru que sur celui cuit.</p></div>",
        imatge: "al-9.png"
    },
    {
        id: 10,
        nom_ca: "Mostassa i derivats",
        nom_es: "Mostaza y derivados",
        nom_en: "Mustard and derivatives",
        nom_fr: "Moutarde et dérivés",
        subNom_ca: "Mostassa i productes derivats",
        subNom_es: "Mostaza y productos derivados",
        subNom_en: "Mustard and mustard products",
        subNom_fr: "Moutarde et produits dérivés",
        descripcio_ca: "<div class='alergens'><p>Es considera substància al·lergògena tota la planta, tant les fulles com la tija i les llavors.</p></div>",
        descripcio_es: "<div class='alergens'><p>Se considera sustancia alergénica toda la planta, tanto las hojas como el tallo y las semillas.</p></div>",
        descripcio_en: "<div class='alergens'><p>The entire plant, including the leaves, stem, and seeds, is considered an allergenic substance.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Toute la plante, y compris les feuilles, la tige et les graines, est considérée comme une substance allergénique.</p></div>",
        imatge: "al-10.png"

    },
    {
        id: 11,
        nom_ca: "Grans de sèsam i productes que el contenen",
        nom_es: "Semillas de sésamo y productos que lo contienen",
        nom_en: "Sesame seeds and products containing them",
        nom_fr: "Graines de sésame et produits les contenant",
        subNom_ca: "Grans de sèsam i productes que contenen grans de sèsam",
        subNom_es: "Semillas de sésamo y productos que contienen semillas de sésamo",
        subNom_en: "Sesame seeds and products containing sesame seeds",
        subNom_fr: "Graines de sésame et produits les contenant",
        descripcio_ca: "<div class='alergens'><p>Es pot trobar als pans, a les amanides, a les salses, a l’humus, als falafels, al tahini...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se puede encontrar en panes, ensaladas, salsas, hummus, falafel, tahini...</p></div>",
        descripcio_en: "<div class='alergens'><p>It can be found in breads, salads, sauces, hummus, falafel, tahini...</p></div>",
        descripcio_fr: "<div class='alergens'><p>On peut en trouver dans les pains, les salades, les sauces, le houmous, le falafel, le tahini...</p></div>",
        imatge: "al-11.png"
    },
    {
        id: 12,
        nom_ca: "Diòxid de sofre i sulfits",
        nom_es: "Dióxido de azufre y sulfitos",
        nom_en: "Sulfur dioxide and sulfites",
        nom_fr: "Dioxyde de soufre et sulfites",
        subNom_ca: "Anhídrid sulfurós i sulfits en quantitats superiors a 10 mg/kg o 10 mg/L (SO2)",
        subNom_es: "Dióxido de azufre y sulfitos en cantidades superiores a 10 mg/kg o 10 mg/L (SO2)",
        subNom_en: "Sulphur dioxide and sulphites at concentrations above 10 mg/kg or 10 mg/L (SO2)",
        subNom_fr: "Dioxyde de soufre et sulfites à des concentrations supérieures à 10 mg/kg ou 10 mg/L (SO2)",
        descripcio_ca: "<div class='alergens'><p>Es fan servir com a conservants als crustacis, a les fruites dessecades, als productes carnis, als refrescos, als sucs i conserves vegetals, al vi, a la cervesa, al vinagre, a la sidra, a les salses de mostassa...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se utilizan como conservantes en crustáceos, frutas deshidratadas, productos cárnicos, refrescos, jugos y conservas vegetales, vino, cerveza, vinagre, sidra, salsas de mostaza...</p></div>",
        descripcio_en: "<div class='alergens'><p>They are used as preservatives in crustaceans, dried fruits, meat products, soft drinks, juices and vegetable preserves, wine, beer, vinegar, cider, mustard sauces...</p></div>",
        descripcio_fr: "<div class='alergens'><p>Ils sont utilisés comme conservateurs dans les crustacés, les fruits séchés, les produits carnés, les boissons gazeuses, les jus et les conserves de légumes, le vin, la bière, le vinaigre, le cidre, les sauces à la moutarde...</p></div>",
        imatge: "al-12.png"
    },
    {
        id: 13,
        nom_ca: "Mol·luscs i derivats",
        nom_es: "Moluscos y derivados",
        nom_en: "Molluscs and derivatives",
        nom_fr: "Mollusques et dérivés",
        subNom_ca: "Mol·luscs i productes a base de mol·luscs",
        subNom_es: "Moluscos y productos a base de moluscos",
        subNom_en: "Molluscs and mollusc-based products",
        subNom_fr: "Mollusques et produits à base de mollusques",
        descripcio_ca: "<div class='alergens'><p>La proteïna al·lergògena principal que es troba als mol·luscs (gasteròpodes, bivalves o cefalòpodes) és la tropomiosina, la mateixa que en els crustacis, i són freqüents els casos d’al·lèrgies encreuades entre mol·luscs i crustacis. A més de consumir-se tal qual, s’utilitzen com a ingredients de determinats preparats, així com en alguns productes com el surimi.</p><p>Es poden trobar en cremes, salses, plats preparats, etc.</p></div>",
        descripcio_es: "<div class='alergens'><p>La principal proteína alergénica que se encuentra en los moluscos (gasterópodos, bivalvos o cefalópodos) es la tropomiosina, la misma que en los crustáceos, y son frecuentes los casos de alergias cruzadas entre moluscos y crustáceos. Además de consumirse tal cual, se utilizan como ingredientes de determinados preparados, así como en algunos productos como el surimi.</p><p>Se pueden encontrar en cremas, salsas, platos preparados, etc.</p></div>",
        descripcio_en: "<div class='alergens'><p>The main allergenic protein found in mollusks (gastropods, bivalves or cephalopods) is tropomyosin, the same as in crustaceans, and cross-reactivity between mollusks and crustaceans is common. In addition to being consumed as is, they are used as ingredients in certain preparations, as well as in some products like surimi.</p><p>They can be found in creams, sauces, prepared dishes, etc.</p></div>",
        descripcio_fr: "<div class='alergens'><p>La principale protéine allergénique présente dans les mollusques (gastéropodes, bivalves ou céphalopodes) est la tropomyosine, la même que dans les crustacés, et il est fréquent que des allergies croisées se produisent entre mollusques et crustacés. En plus d'être consommés tels quels, ils sont utilisés comme ingrédients dans certaines préparations, ainsi que dans certains produits tels que le surimi.</p><p>Ils peuvent être trouvés dans des crèmes, des sauces, des plats préparés, etc.</p></div>",
        imatge: "al-13.png"
    },
    {
        id: 14,
        nom_ca: "Tramussos i derivats",
        nom_es: "Tramuces y derivados",
        nom_en: "Lumps and derivatives",
        nom_fr: "Graines de lupin et dérivés",
        subNom_ca: "Tramussos i productes a base de tramussoss",
        subNom_es: "Tramuces y productos a base de tramuces",
        subNom_en: "Lumps and lumps-based products",
        subNom_fr: "Graines de lupin et produits à base de lupin",
        descripcio_ca: "<div class='alergens'><p>Es tracta d’una planta lleguminosa que té més de 450 espècies diferents; s’hi han documentat casos de reaccions al·lèrgiques directes (a vegades greus) i s’ha demostrat el risc de reactivitat encreuada amb els cacauets.</p><p></p><p>Des de fa uns anys la farina de tramussos s’afegeix a la farina de blat per a l’elaboració de productes de pa.</p><p>Es pot trobar en alguns pans, pastissos, pastes, farines...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se trata de una planta leguminosa que tiene más de 450 especies distintas; se han documentado casos de reacciones alérgicas directas (a veces graves) y se ha demostrado el riesgo de reactividad cruzada con los cacahuetes.</p><p>Desde hace unos años la harina de altramuces se añade a la harina de trigo para la elaboración de productos de pan.</p><p>Se puede encontrar en algunos panes, pasteles, pastas, harinas...</p></div>",
        descripcio_en: "<div class='alergens'><p>It is a leguminous plant that has more than 450 different species; cases of direct allergic reactions (sometimes severe) have been documented and the risk of cross-reactivity with peanuts has been demonstrated.</p><p>For some years lupine flour has been added to wheat flour to make bread products.</p><p>It can be found in some breads, cakes, pastas, flours...</p></div>",
        descripcio_fr: "<div class='alergens'><p>C'est une plante légumineuse qui compte plus de 450 espèces différentes ; des cas de réactions allergiques directes (parfois sévères) ont été documentés et le risque de réactivité croisée avec l'arachide a été démontré.</p><p>Depuis quelques années, la farine de lupin est ajoutée à la farine de blé pour fabriquer des produits de panification.</p><p>On en retrouve dans certains pains, gâteaux, pâtes, farines...</p></div>",
        imatge: "al-14.png"
    }
];