ALERGENS = [
    {
        id: 0
    },
    {
        id: 1,
        nom_ca: "Cereals que contenen gluten",
        nom_es: "Cereales que contienen gluten",
        nom_en: "Cereals containing gluten",
        nom_fr: "Céréales contenant du gluten",
        subNom_ca: "Cereals que contenen gluten: blat, ordi sègol, civada, espelta, kamut",
        subNom_es: "Cereales que contienen gluten: trigo, cebada, centeno, espelta, kamut",
        subNom_en: "Cereals containing gluten: wheat, barley, rye, spelt, kamut",
        subNom_fr: "Céréales contenant du gluten : blé, orge, seigle, épeautre, kamut",
        descripcio_ca: "<div class='alergens'><p>El gluten és una proteïna que es troba en el blat, ordi, sègol, civada, espelta, kamut i varietats híbrides i productes derivats d’aquests cereals. Es pot trobar en aliments que contenen farina, midons, pa, pasta, pa ratllat, galetes, pastisseria, salses, sopes, productes carnis, embotits, pizzes, croquetes... El seitan és un preparat fet a base de gluten de blat.</p><p><strong>Malaltia celíaca:</strong> La celiaquia o intolerància al gluten és una malaltia de caràcter permanent que provoca, en individus genèticament predisposats, una atròfia de les vellositats de l’intestí prim, que afecta la capacitat d’absorbir els nutrients dels aliments. La sensibilitat al gluten és variable entre els individus celíacs. Així, després de diversos estudis, es considera que el llindar de tolerància de gluten varia entre els 10 mg i els 50 mg de gluten al dia.</p><p>Els estudis més recents demostren que aquesta malaltia afecta aproximadament 1 de cada 100 persones, i la celiaquia és la malaltia crònica intestinal més freqüent en el món occidental.</p><p><strong>Al·lèrgia als cereals</strong>: Els cereals també poden causar al·lèrgies alimentàries, encara que no són comunes en la població. Els al·lèrgens dels cereals poden reaccionar de forma encreuada amb els al·lèrgens del pol·len.</p></div>",
        descripcio_es: "<div class='alergens'><p>El gluten es una proteína que se encuentra en el trigo, cebada, centeno, avena, espelta, kamut y variedades híbridas y productos derivados de estos cereales.</p><p>Se puede encontrar en alimentos que contienen harina, almidones, pan, pasta, pan rallado, galletas, pastelería, salsas, sopas, productos cárnicos, embutidos, pizzas, croquetas... El seitán es un preparado hecho a base de gluten de trigo.</p><p><strong>Enfermedad celíaca</strong>: La celiaquía o intolerancia al gluten es una enfermedad de carácter permanente que provoca, en individuos genéticamente predispuestos, una atrofia de las vellosidades del intestino delgado, que afecta a la capacidad de absorber los nutrientes de los alimentos. La sensibilidad al gluten es variable entre los individuos celíacos. Así, después de varios estudios, se considera que el umbral de tolerancia de gluten varía entre los 10 mg y los 50 mg de gluten al día.</p><p>Los estudios más recientes demuestran que esta enfermedad afecta aproximadamente a 1 de cada 100 personas, y la celiaquía es la enfermedad crónica intestinal más frecuente en el mundo occidental.</p><p><strong>Alergia a los cereales</strong>: Los cereales también pueden causar alergias alimentarias, aunque no son comunes en la población. Los alérgenos de los cereales pueden reaccionar de forma cruzada con los alérgenos del polen.</p></div>",
        descripcio_en: "<div class='alergens'><p>Gluten is a protein found in wheat, barley, rye, oats, spelt, kamut and hybrid varieties and products derived from these cereals. It can be found in foods containing flour, starches, bread, pasta, breadcrumbs, biscuits, pastries, sauces, soups, meat products, sausages, pizzas, croquettes... Seitan is a preparation made from wheat gluten.</p><p><strong>Celiac disease</strong> or gluten intolerance is a permanent disease that causes, in genetically predisposed individuals, an atrophy of the villi of the small intestine, which affects the ability to absorb nutrients from food. Gluten sensitivity is variable among celiac individuals. Thus, after several studies, it is considered that the threshold of gluten tolerance varies between 10 mg and 50 mg of gluten per day. The most recent studies show that this disease affects approximately 1 in 100 people, and celiac disease is the most common chronic intestinal disease in the Western world.</p><p>Cereals can also cause food allergies, although they are not common in the population. Cereal allergens can cross-react with pollen allergens.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Le gluten est une protéine présente dans le blé, l'orge, le seigle, l'avoine, l'épeautre, le kamut et les variétés hybrides et les produits dérivés de ces céréales.</p><p>On le trouve dans les aliments contenant de la farine, des féculents, du pain, des pâtes, de la chapelure, des biscuits, des viennoiseries, des sauces, des soupes, des charcuteries, des saucisses, des pizzas, des croquettes... Le seitan est une préparation à base de gluten de blé.</p><p><strong>Maladie coeliaque</strong>: La maladie coeliaque ou intolérance au gluten est une maladie permanente qui provoque, chez les individus génétiquement prédisposés, une atrophie des villosités de l'intestin grêle, qui affecte la capacité à absorber les nutriments des aliments. La sensibilité au gluten est variable chez les personnes coeliaques. Ainsi, après plusieurs études, on considère que le seuil de tolérance au gluten varie entre 10 mg et 50 mg de gluten par jour.</p><p>Les études les plus récentes montrent que cette maladie touche environ 1 personne sur 100 et que la maladie cœliaque est la maladie intestinale chronique la plus répandue dans le monde occidental.</p><p><strong>Allergie aux céréales</strong>: Les céréales peuvent également provoquer des allergies alimentaires, bien qu'elles ne soient pas courantes dans la population. Les allergènes céréaliers peuvent réagir de manière croisée avec les allergènes polliniques.</p></div>",
        imatge: "al-1.png"
    },
    {
        id: 2,
        nom_ca: "Crustacis i productes amb crustacis",
        nom_es: "Crustáceos y productos con crustáceos",
        nom_en: "Crustaceans and products with crustaceans",
        nom_fr: "Crustacés et produits à base de crustacés",
        subNom_ca: "Crustacis i productes que contenen crustacis",
        subNom_es: "Crustáceos y productos que contienen crustáceos",
        subNom_en: "Crustaceans and products containing crustaceans",
        subNom_fr: "Crustacés et produits contenant des crustacés",
        descripcio_ca: "<div class='alergens'><p>En aquest grup d’al·lèrgens s’inclouen totes les espècies de crustacis (gambes, els escamarlans, els llagostins, els crancs, la llagosta, el llamàntol, etc.). Es tracta d’una al·lèrgia força comuna i, a causa de la reactivitat encreuada entre espècies, un mateix individu pot reaccionar a diferents espècies de crustacis. A més, algunes persones poden tenir reaccions per inhalació de vapors de cocció i algunes altres també poden ser al·lèrgiques als mol·luscs.</p></div>",
        descripcio_es: "<div class='alergens'><p>Este grupo de alérgenos incluye todas las especies de crustáceos (camarones, langostinos, cangrejos, langosta, nécoras, etc.). Se trata de una alergia bastante común y, debido a la reactividad cruzada entre especies, una misma persona puede reaccionar a diferentes especies de crustáceos. Además, algunas personas pueden tener reacciones por inhalación de vapores de cocción y algunas otras también pueden ser alérgicas a los moluscos.</p></div>",
        descripcio_en: "<div class='alergens'><p>This group of allergens includes all species of crustaceans (shrimp, prawns, crabs, lobster, crayfish, etc.). It is a fairly common allergy and, due to cross-reactivity between species, the same individual can react to different species of crustaceans. In addition, some people may have reactions from inhaling cooking vapors and some others may also be allergic to mollusks.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Ce groupe d'allergènes comprend toutes les espèces de crustacés (crevettes, langoustines, crabes, homards, écrevisses, etc.). C'est une allergie assez courante et, en raison de la réactivité croisée entre les espèces, une même personne peut réagir à différentes espèces de crustacés. De plus, certaines personnes peuvent avoir des réactions en inhalant des vapeurs de cuisson et certaines autres peuvent également être allergiques aux mollusques.</p></div>",
        imatge: "al-2.png"
    },
    {
        id: 3,
        nom_ca: "Ous i productes derivats",
        nom_es: "Huevos y productos derivados",
        nom_en: "Eggs and egg products",
        nom_fr: "Œufs et produits dérivés",
        subNom_ca: "Ous i productes que contenen ou",
        subNom_es: "Huevos y productos que contienen huevo",
        subNom_en: "Eggs and products containing eggs",
        subNom_fr: "Oeufs et produits contenant des œufs",
        descripcio_ca: "<div class='alergens'><p>És una al·lèrgia comuna en infants però que sovint desapareix a partir dels tres anys d’edat. Els ous poden causar reaccions anafilàctiques en algunes persones (reaccions que afecten a la vegada diversos òrgans o sistemes en pocs minuts). Hi ha reactivitat encreuada amb ous d’altres espècies com ara l’ànec o la guatlla. </p><p>Es pot trobar als productes de pastisseria, pasta, plats preparats, productes carnis, salses, condiments, caramels, flams, gelats, alguns formatges, sopes...</p></div>",
        descripcio_es: "<div class='alergens'><p>Es una alergia común en niños pero que a menudo desaparece a partir de los tres años de edad. Los huevos pueden causar reacciones anafilácticas en algunas personas (reacciones que afectan a la vez diversos órganos o sistemas en pocos minutos). Existe reactividad cruzada con huevos de otras especies como el pato o la codorniz.</p><p>Se puede encontrar en productos de pastelería, pasta, platos preparados, productos cárnicos, salsas, condimentos, caramelos, flanes, helados, algunos quesos, sopas...</p></div>",
        descripcio_en: "<div class='alergens'><p>It is a common allergy in children but often disappears after the age of three. Eggs can cause anaphylactic reactions in some people (reactions that affect several organs or systems at the same time in a few minutes). There is cross-reactivity with eggs from other species such as duck or quail.</p><p>It can be found in bakery products, pasta, prepared dishes, meat products, sauces, condiments, candies, custards, ice creams, some cheeses, soups...</p></div>",
        descripcio_fr: "<div class='alergens'><p>C'est une allergie courante chez les enfants mais qui disparaît souvent à partir de l'âge de trois ans. Les œufs peuvent causer des réactions anaphylactiques chez certaines personnes (réactions qui affectent plusieurs organes ou systèmes en même temps en quelques minutes). Il y a une réactivité croisée avec les œufs d'autres espèces comme le canard ou la caille.</p><p>On peut le trouver dans les produits de boulangerie, les pâtes, les plats préparés, les produits carnés, les sauces, les condiments, les bonbons, les flans, les crèmes glacées, certains fromages, les soupes...</p></div>",
        imatge: "al-3.png"
    },
    {
        id: 4,
        nom_ca: "Peix i productes amb peix",
        nom_es: "Pescado y productos con pescado",
        nom_en: "Fish and fish products",
        nom_fr: "Poissons et produits à base de poissons",
        subNom_ca: "Peix i productes que contenen peix",
        subNom_es: "Pescado y productos que contienen pescado",
        subNom_en: "Fish and products containing fish",
        subNom_fr: "Poisson et produits contenant du poisson",
        descripcio_ca: "<div class='alergens'><p>L'augment del seu consum en el món occidental fa que l'al·lèrgia al peix i derivats hagi adquirit més importància en nens i adults.</p><p>Es considera al·lergen qualsevol espècie de peix ja que la majoria d'espècies poden presentar reactivitat encreuada entre si, i per tant cap no es pot considerar segura per a una persona al·lèrgica.</p><p>Es pot trobar a les salses de peix, condiments preparats, brous, pastilles per al brou, pizzes, croquetes, surimi...</p></div>",
        descripcio_es: "<div class='alergens'><p>El aumento de su consumo en el mundo occidental hace que la alergia al pescado y derivados haya adquirido más importancia en niños y adultos.</p><p>Se considera alérgeno cualquier especie de pescado ya que la mayoría de especies pueden presentar reactividad cruzada entre sí, y por tanto ninguna se puede considerar segura para una persona alérgica.</p><p>Se puede encontrar en las salsas de pescado, condimentos preparados, caldos, pastillas para el caldo, pizzas, croquetas, surimi...</p></div>",
        descripcio_en: "<div class='alergens'><p>The increase in its consumption in the Western world has made fish and seafood allergy more important in children and adults.</p><p>Any species of fish is considered an allergen since most species can present cross-reactivity between them, and therefore none can be considered safe for an allergic person.</p><p>It can be found in fish sauces, prepared condiments, broths, broth cubes, pizzas, croquettes, surimi...</p></div>",
        descripcio_fr: "<div class='alergens'><p>L'augmentation de sa consommation dans le monde occidental a fait que l'allergie au poisson et dérivés a acquis plus d'importance chez les enfants et les adultes.</p><p>Toute espèce de poisson est considérée comme un allergène car la plupart des espèces peuvent présenter une réactivité croisée entre elles, et donc aucune ne peut être considérée comme sûre pour une personne allergique.</p><p>On peut le trouver dans les sauces de poisson, les condiments préparés, les bouillons, les cubes de bouillon, les pizzas, les croquettes, le surimi...</p></div>",
        imatge: "al-4.png"
    },
    {
        id: 5,
        nom_ca: "Cacauets i derivats",
        nom_es: "Cacahuetes y derivados",
        nom_en: "Peanuts and derivatives",
        nom_fr: "Arachides et dérivés",
        subNom_ca: "Cacauet i productes que contenen cacauet",
        subNom_es: "Cacahuete y productos que contienen cacahuetes",
        subNom_en: "Peanuts and products containing peanuts",
        subNom_fr: "Arachide et produits contenant des arachides",
        descripcio_ca: "<div class='alergens'><p>Pertanyen a la família de les lleguminoses i són els causants principals d’anafilaxi i els que provoquen reaccions al·lèrgiques més greus. És habitual que les persones al·lèrgiques al cacauet també reaccionin a la fruita seca i a altres membres de la família de les lleguminoses tals com la soja o el tramús. Els tractaments de calor augmenten l’efecte al·lergogen del cacauet.</p></div>",
        descripcio_es: "<div class='alergens'><p>Pertenecen a la familia de las leguminosas y son los causantes principales de anafilaxia y de las reacciones alérgicas más graves. Es habitual que las personas alérgicas al cacahuete también reaccionen a la fruta seca y a otros miembros de la familia de las leguminosas como la soja o el altramuz. Los tratamientos de calor aumentan el efecto alergénico del cacahuete.</p></div>",
        descripcio_en: "<div class='alergens'><p>Belonging to the family of legumes, peanuts are the main cause of anaphylaxis and the most severe allergic reactions. It is common for people allergic to peanuts to also react to tree nuts and other members of the legume family such as soy or lupin. Heat treatments increase the allergenic effect of peanuts.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Appartenant à la famille des légumineuses, les cacahuètes sont la principale cause d’anaphylaxie et des réactions allergiques les plus graves. Il est courant que les personnes allergiques aux cacahuètes réagissent également aux fruits à coque et à d'autres membres de la famille des légumineuses tels que le soja ou le lupin. Les traitements thermiques augmentent l'effet allergène des cacahuètes.</p></div>",
        imatge: "al-5.png"
    },
    {
        id: 6,
        nom_ca: "Soja i productes amb soja",
        nom_es: "Soja y productos con soja",
        nom_en: "Soy and soy products",
        nom_fr: "Soja et produits à base de soja",
        subNom_ca: "Soja i productes que contenen soja",
        subNom_es: "Soja y productos que contienen soja",
        subNom_en: "Soybeans and products containing soybeans",
        subNom_fr: "Soja et produits contenant du soja",
        descripcio_ca: "<div class='alergens'><p>Pertany a la família de les lleguminoses, i pot tenir reactivitat encreuada amb altres llegums (inclòs el cacauet). També s’ha arribat a descriure la reacció encreuada amb les proteïnes de vaca. És una al·lèrgia que es presenta de forma ocasional en adults, en nens és més habitual però sol desaparèixer a partir dels dos anys d’edat.</p><p>A més de la salsa de soja, podem trobar-ne en alguns productes, com ara, a altres tipus de salses, condiments, a les postres, als gelats i als productes carnis; productes derivats de la soja com aïllats de proteïna de soja, els concentrats de proteïna de soja i la lecitina de soja que es fan servir com a  ingredients en nombrosos plats i també a la xocolata. Són derivats de la soja el tofu, el miso i el tempeh.</p></div>",
        descripcio_es: "<div class='alergens'><p>Pertenece a la familia de las leguminosas, y puede tener reactividad cruzada con otras legumbres (incluyendo el cacahuete). También se ha descrito la reacción cruzada con las proteínas de vaca. Es una alergia que se presenta de forma ocasional en adultos, en niños es más habitual pero suele desaparecer a partir de los dos años de edad.</p><p>Además de la salsa de soja, podemos encontrarla en algunos productos, como en otros tipos de salsas, condimentos, en los postres, en los helados y en los productos cárnicos; productos derivados de la soja como aislados de proteína de soja, los concentrados de proteína de soja y la lecitina de soja que se utilizan como ingredientes en numerosos platos y también en el chocolate. Son derivados de la soja el tofu, el miso y el tempeh.</p></div>",
        descripcio_en: "<div class='alergens'><p>It belongs to the legume family and can cross-react with other legumes (including peanuts). Cross-reactivity with cow proteins has also been described. It is an allergy that occurs occasionally in adults, is more common in children but usually disappears after the age of two.</p><p>In addition to soy sauce, it can be found in some products, such as other types of sauces, condiments, desserts, ice creams, and meat products; soy derivatives such as soy protein isolates, soy protein concentrates, and soy lecithin are used as ingredients in numerous dishes and also in chocolate. Soy products include tofu, miso, and tempeh.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Il appartient à la famille des légumineuses et peut avoir une réaction croisée avec d'autres légumineuses (y compris les arachides). La réaction croisée avec les protéines de vache a également été décrite. C'est une allergie qui survient occasionnellement chez l'adulte, elle est plus fréquente chez l'enfant mais disparaît généralement après l'âge de deux ans.</p><p>En plus de la sauce soja, on peut la trouver dans certains produits, comme d'autres types de sauces, condiments, desserts, glaces et produits carnés ; produits dérivés du soja tels que les isolats de protéines de soja, les concentrés de protéines de soja et la lécithine de soja qui sont utilisés comme ingrédients dans de nombreux plats ainsi que dans le chocolat. Le tofu, le miso et le tempeh sont dérivés du soja.</p></div>",
        imatge: "al-6.png"
    },
    {
        id: 7,
        nom_ca: "Llet i derivats, inclosa la lactosa",
        nom_es: "Leche y derivados, incluida la lactosa",
        nom_en: "Milk and dairy products, including lactose",
        nom_fr: "Lait et produits laitiers, y compris le lactose",
        subNom_ca: "Llet i els seus derivats (inclosa la lactosa)",
        subNom_es: "Leche y sus derivados (incluida la lactosa)",
        subNom_en: "Milk and its derivatives (including lactose)",
        subNom_fr: "Lait et ses dérivés (y compris le lactose)",
        descripcio_ca: "<div class='alergens'><p>Al·lèrgia a les proteïnes de la llet</p><p>Aquesta al·lèrgia és la més comuna de totes en nens; afecta entre el 2% i el 7% dels nadons, tot i que un 87% dels infants es curen a l’edat de tres anys. Hi ha un nivell alt de reactivitat encreuada amb les proteïnes de llet d’altres mamífers com la cabra, l’ovella i la búfala. Els símptomes són suaus tot i que en individus molt sensibles poden causar un xoc anafilàctic.</p><p>Intolerància a la lactosa</p><p>La lactosa és un sucre que està present en totes les llets de mamífers: vaca, cabra, ovella. És un disacàrid natural, que es compon de glucosa i galactosa. La intolerància a la lactosa no és una reacció al·lèrgica i no dóna reacció anafilàctica. Està provocada per una capacitat reduïda o per mancança de la lactasa, enzim que es troba a l’intestí prim i que és capaç de trencar la lactosa.</p><p>Els nivells de tolerància dependran dels nivells de lactasa de cada individu, per exemple els adults amb lactasa reduïda podrien tolerar fins a 10 g al dia (quantitat que es troba en 200 ml de llet).</p><p>La lactosa pot contenir residus de proteïnes de la llet a conseqüència del procés d’obtenció, i per tant la lactosa pot no ser apta per a les persones al·lèrgiques a la llet.</p><p>Inclou, entre d’altres, la llet de vaca, cabra, ovella i búfala. A més, també s’hi inclouen els productes làctics, com ara la mantega, el formatge, els iogurts, la crema de llet, els flams, les natilles, els gelats... Es pot trobar en una àmplia varietat d’aliments: postres, embotits, salses, pans, xocolates, croquetes, sopes...</p></div>",
        descripcio_es: "<div class='alergens'><p>La alergia a las proteínas de la leche es la más común de todas en niños; afecta entre el 2% y el 7% de los bebés, aunque un 87% de los niños se curan a la edad de tres años. Hay un alto nivel de reactividad cruzada con las proteínas de leche de otros mamíferos como la cabra, la oveja y la búfala. Los síntomas son suaves aunque en individuos muy sensibles pueden causar un shock anafiláctico.</p><p>La intolerancia a la lactosa no es una reacción alérgica y no causa una reacción anafiláctica. Está provocada por una capacidad reducida o por falta de la lactasa, enzima que se encuentra en el intestino delgado y que es capaz de descomponer la lactosa.</p><p>Los niveles de tolerancia dependerán de los niveles de lactasa de cada individuo, por ejemplo, los adultos con lactasa reducida podrían tolerar hasta 10 g al día (cantidad que se encuentra en 200 ml de leche).</p><p>La lactosa puede contener residuos de proteínas de la leche como resultado del proceso de obtención, y por lo tanto la lactosa puede no ser apta para personas alérgicas a la leche.</p><p>Se incluye, entre otros, la leche de vaca, cabra, oveja y búfala. Además, también se incluyen los productos lácteos, como la mantequilla, el queso, los yogures, la crema de leche, los flanes, las natillas, los helados... Se puede encontrar en una amplia variedad de alimentos: postres, embutidos, salsas, panes, chocolates, croquetas, sopas...</p></div>",
        descripcio_en: "<div class='alergens'><p>Milk protein allergy is the most common of all in children; it affects between 2% and 7% of infants, although 87% of children are cured by the age of three. There is a high level of cross-reactivity with milk proteins from other mammals such as goats, sheep, and buffalo. Symptoms are mild although in very sensitive individuals they can cause anaphylactic shock.</p><p>Lactose intolerance is not an allergic reaction and does not cause anaphylactic reaction. It is caused by reduced capacity or lack of lactase, an enzyme found in the small intestine that is able to break down lactose. Tolerance levels will depend on the lactase levels of each individual, for example, adults with reduced lactase may tolerate up to 10 g per day (the amount found in 200 ml of milk).</p><p>Lactose may contain residues of milk proteins as a result of the production process, and therefore lactose may not be suitable for people with milk allergies. It includes, among others, cow's, goat's, sheep's and buffalo's milk. In addition, dairy products such as butter, cheese, yoghurts, milk cream, custards, creams, ice creams, etc. are also included. It can be found in a wide variety of foods: desserts, sausages, sauces, breads, chocolates, croquettes, soups...</p></div>",
        descripcio_fr: "<div class='alergens'><p>Allergie aux protéines du lait</p><p>Cette allergie est la plus courante chez les enfants ; elle touche entre 2% et 7% des nourrissons, bien que 87% des enfants soient guéris à l’âge de trois ans. Il y a un niveau élevé de réactivité croisée avec les protéines de lait d’autres mammifères tels que la chèvre, le mouton et le buffle. Les symptômes sont légers bien qu’ils puissent causer un choc anaphylactique chez les individus très sensibles.</p><p>Intolérance au lactose</p><p>Le lactose est un sucre présent dans tous les laits de mammifères : vache, chèvre, mouton. C’est un disaccharide naturel, composé de glucose et de galactose. L’intolérance au lactose n’est pas une réaction allergique et ne provoque pas de réaction anaphylactique. Elle est causée par une capacité réduite ou un manque de lactase, une enzyme présente dans l’intestin grêle capable de décomposer le lactose.</p><p>Les niveaux de tolérance dépendront des niveaux de lactase de chaque individu, par exemple les adultes avec une lactase réduite pourraient tolérer jusqu’à 10 g par jour (quantité trouvée dans 200 ml de lait).</p><p>Le lactose peut contenir des résidus de protéines de lait en raison du processus d’obtention, et donc le lactose peut ne pas être adapté aux personnes allergiques au lait.</p><p>Il comprend, entre autres, le lait de vache, de chèvre, de mouton et de buffle. En outre, les produits laitiers tels que le beurre, le fromage, les yaourts, la crème, les flans, les crèmes dessert, les glaces, etc., sont également inclus. On peut le trouver dans une large variété d’aliments : desserts, charcuterie, sauces, pains, chocolats, croquettes, soupes...</p></div>",
        imatge: "al-7.png"
    },
    {
        id: 8,
        nom_ca: "Fruits secs i derivats",
        nom_es: "Frutos secos y derivados",
        nom_en: "Nuts and derivatives",
        nom_fr: "Fruits secs et dérivés",
        subNom_ca: "Fruita seca de clofolla: ametlles, avellanes, nous, anacards, pacanes, nous del Brasil, festucs, macadàmies i nous d’Austràlia.",
        subNom_es: "Frutos secos de cáscara: almendras, avellanas, nueces, anacardos, pacanas, nueces de Brasil, pistachos, macadamias y nueces de Australia.",
        subNom_en: "Tree nuts: almonds, hazelnuts, walnuts, cashews, pecans, Brazil nuts, pistachios, macadamia nuts, and Australian nuts.",
        subNom_fr: "Fruits à coque : amandes, noisettes, noix, noix de cajou, pacanes, noix du Brésil, pistaches, noix de macadamia et noix d'Australie.",
        descripcio_ca: "<div class='alergens'><p>En aquest grup d’al·lèrgens s’inclouen les ametlles (Amygdalus communis L.), avellanes (Corylus avellana), nous (Juglans regia), anacards (Anacardium occidentale), pacanes [Carya illinoiesis (Wangenh.) K. Koch], nous del Brasil (Bertholletia excelsa), festucs (Pistacia vera), macadàmies i nous d’Austràlia (Macadamia ternifolia) i els productes derivats.</p><p>La fruita seca és causa freqüent de reacció al·lèrgica i, en general, les persones sensibles reaccionen a més d’un fruit, així com al cacauet. El torrat podria reduir en part l’al·lergenicitat de les avellanes, però es desconeix l’efecte en l’altra fruita seca.</p><p>Es troben als massapans, als pralinés, a les xocolates, als torrons, a les salses preparades, als condiments.</p></div>",
        descripcio_es: "<div class='alergens'><p>Este grupo de alérgenos incluye las almendras (Amygdalus communis L.), avellanas (Corylus avellana), nueces (Juglans regia), anacardos (Anacardium occidentale), pacanas [Carya illinoiesis (Wangenh.) K. Koch], nueces de Brasil (Bertholletia excelsa), pistachos (Pistacia vera), macadamias y nueces de Australia (Macadamia ternifolia) y sus productos derivados.</p><p>La fruta seca es una causa frecuente de reacción alérgica y, en general, las personas sensibles reaccionan a más de una fruta, así como al cacahuete. El tostado podría reducir en parte la alergenicidad de las avellanas, pero se desconoce el efecto en la otra fruta seca.</p><p>Se encuentran en mazapanes, pralinés, chocolates, turrones, salsas preparadas, condimentos.</p></div>",
        descripcio_en: "<div class='alergens'><p>This group of allergens includes almonds (Amygdalus communis L.), hazelnuts (Corylus avellana), walnuts (Juglans regia), cashews (Anacardium occidentale), pecans [Carya illinoiesis (Wangenh.) K. Koch], Brazil nuts (Bertholletia excelsa), pistachios (Pistacia vera), macadamias and Australian nuts (Macadamia ternifolia) and their derived products.</p><p>Dried fruit is a frequent cause of allergic reaction and, in general, sensitive individuals react to more than one fruit, as well as to peanuts. Roasting could partially reduce the allergenicity of hazelnuts, but the effect on other dried fruit is unknown.</p><p>They can be found in marzipans, pralines, chocolates, nougats, prepared sauces, seasonings.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Ce groupe d'allergènes comprend les amandes (Amygdalus communis L.), les noisettes (Corylus avellana), les noix (Juglans regia), les noix de cajou (Anacardium occidentale), les noix de pécan [Carya illinoiesis (Wangenh.) K. Koch], les noix du Brésil (Bertholletia excelsa), les pistaches (Pistacia vera), les noix de macadamia et les noix d'Australie (Macadamia ternifolia), ainsi que les produits dérivés.</p><p>Les fruits secs sont une cause fréquente de réaction allergique et, en général, les personnes sensibles réagissent à plus d'un fruit, ainsi qu'aux arachides. Le rôtissage pourrait réduire partiellement l'allergénicité des noisettes, mais l'effet sur les autres fruits secs est inconnu.</p><p>On les retrouve dans les massepains, les pralinés, les chocolats, les nougats, les sauces préparées et les condiments.</p></div>",
        imatge: "al-8.png"
    },
    {
        id: 9,
        nom_ca: "Api i derivats",
        nom_es: "Apio y derivados",
        nom_en: "Celery and derivatives",
        nom_fr: "Céleri et dérivés",
        subNom_ca: "Api i productes derivats",
        subNom_es: "Apio y productos derivados",
        subNom_en: "Celery and celery products",
        subNom_fr: "Céleri et produits dérivés",
        descripcio_ca: "<div class='alergens'><p>Tant la planta com els brots de l’arrel es consideren substàncies al·lergògenes, i l’al·lèrgia se sol presentar amb més freqüència sobre el producte cru que sobre el cuinat. Freqüent als països de l’Europa Central i França. Hi ha reactivitat encreuada amb l’api-rave.</p></div>",
        descripcio_es: "<div class='alergens'><p>Tanto la planta como los brotes de la raíz se consideran sustancias alergénicas, y la alergia suele presentarse con más frecuencia sobre el producto crudo que sobre el cocinado. Frecuente en los países de Europa Central y Francia. Existe reactividad cruzada con el apio-nabo.</p></div>",
        descripcio_en: "<div class='alergens'><p>Both the plant and the root sprouts are considered allergenic substances, and allergy tends to occur more frequently on the raw product than on the cooked one. Common in countries of Central Europe and France. Cross-reactivity with celeriac may occur.</p></div>",
        descripcio_fr: "<div class='alergens'><p>Tant la plante que les pousses de la racine sont considérées comme des substances allergéniques, et l'allergie se produit généralement plus fréquemment sur le produit cru que sur celui cuit. Fréquent dans les pays d'Europe centrale et en France. Il peut y avoir une réactivité croisée avec le céleri-rave.</p></div>",
        imatge: "al-9.png"
    },
    {
        id: 10,
        nom_ca: "Mostassa i derivats",
        nom_es: "Mostaza y derivados",
        nom_en: "Mustard and derivatives",
        nom_fr: "Moutarde et dérivés",
        subNom_ca: "Mostassa i productes derivats",
        subNom_es: "Mostaza y productos derivados",
        subNom_en: "Mustard and mustard products",
        subNom_fr: "Moutarde et produits dérivés",
        descripcio_ca: "<div class='alergens'><p>Es considera substància al·lergògena tota la planta, tant les fulles com la tija i les llavors. És freqüent a França i Espanya. Es pot trobar als pans, als condiments preparats, a les salses, a les sopes, als productes carnis, als productes marinats...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se considera sustancia alergénica toda la planta, tanto las hojas como el tallo y las semillas. Es frecuente en Francia y España. Se puede encontrar en panes, condimentos preparados, salsas, sopas, productos cárnicos, productos marinados...</p></div>",
        descripcio_en: "<div class='alergens'><p>The entire plant, including the leaves, stem, and seeds, is considered an allergenic substance. It is common in France and Spain. It can be found in breads, prepared seasonings, sauces, soups, meat products, marinated products...</p></div>",
        descripcio_fr: "<div class='alergens'><p>Toute la plante, y compris les feuilles, la tige et les graines, est considérée comme une substance allergénique. C'est courant en France et en Espagne. On peut le trouver dans les pains, les assaisonnements préparés, les sauces, les soupes, les produits carnés, les produits marinés...</p></div>",
        imatge: "al-10.png"
    },
    {
        id: 11,
        nom_ca: "Grans de sèsam i productes que el contenen",
        nom_es: "Semillas de sésamo y productos que lo contienen",
        nom_en: "Sesame seeds and products containing them",
        nom_fr: "Graines de sésame et produits les contenant",
        subNom_ca: "Grans de sèsam i productes que contenen grans de sèsam",
        subNom_es: "Semillas de sésamo y productos que contienen semillas de sésamo",
        subNom_en: "Sesame seeds and products containing sesame seeds",
        subNom_fr: "Graines de sésame et produits contenant des graines de sésame",
        descripcio_ca: "<div class='alergens'><p>Té reactivitat encreuada amb els fruits secs, la soja i el cacauet. Pot causar reaccions adverses molt greus. És una al·lèrgia freqüent en països que en fan un consum elevat, en què l’exposició té lloc en edats primerenques. Es pot trobar als pans, a les amanides, a les salses, a l’humus, als falafels, al tahini...</p></div>",
        descripcio_es: "<div class='alergens'><p>Tiene reactividad cruzada con los frutos secos, la soja y el cacahuete. Puede causar reacciones adversas muy graves. Es una alergia frecuente en países donde se consume mucho, y la exposición se produce en edades tempranas. Se puede encontrar en panes, ensaladas, salsas, hummus, falafel, tahini...</p></div>",
        descripcio_en: "<div class='alergens'><p>It has cross-reactivity with nuts, soy, and peanuts. It can cause very serious adverse reactions. It is a common allergy in countries where it is consumed heavily, and exposure occurs at early ages. It can be found in breads, salads, sauces, hummus, falafel, tahini...</p></div>",
        descripcio_fr: "<div class='alergens'><p>Il a une réactivité croisée avec les noix, le soja et les arachides. Il peut causer des réactions indésirables très graves. C'est une allergie courante dans les pays où il est beaucoup consommé, et l'exposition se produit à un âge précoce. On peut le trouver dans les pains, les salades, les sauces, le houmous, le falafel, le tahini...</p></div>",
        imatge: "al-11.png"
    },
    {
        id: 12,
        nom_ca: "Diòxid de sofre i sulfits",
        nom_es: "Dióxido de azufre y sulfitos",
        nom_en: "Sulfur dioxide and sulfites",
        nom_fr: "Dioxyde de soufre et sulfites",
        subNom_ca: "Anhídrid sulfurós i sulfits en quantitats superiors a 10 mg/kg o 10 mg/L (SO2)",
        subNom_es: "Dióxido de azufre y sulfitos en cantidades superiores a 10 mg/kg o 10 mg/L (SO2)",
        subNom_en: "Sulphur dioxide and sulphites at concentrations above 10 mg/kg or 10 mg/L (SO2)",
        subNom_fr: "Dioxyde de soufre et sulfites à des concentrations supérieures à 10 mg/kg ou 10 mg/L (SO2)",
        descripcio_ca: "<div class='alergens'><p>La prevalença de sensibilitat als sulfits en la població és desconeguda, però sembla que és poc freqüent, llevat de la població asmàtica. La reacció adversa més freqüent és un broncospasme que pot ocórrer pocs minuts després del consum d’un aliment amb sulfits. No s’ha determinat un llindar per sota del qual no es produeixin reaccions adverses, i el límit de 10 mg/kg o litre es correspon amb el límit dels mètodes de detecció de sulfits disponibles actualment.</p><p>Es fan servir com a conservants als crustacis, a les fruites dessecades, als productes carnis, als refrescos, als sucs i conserves vegetals, al vi, a la cervesa, al vinagre, a la sidra, a les salses de mostassa...</p></div>",
        descripcio_es: "<div class='alergens'><p>La prevalencia de sensibilidad a los sulfitos en la población es desconocida, pero parece que es poco frecuente, excepto en la población asmática. La reacción adversa más frecuente es un broncoespasmo que puede ocurrir pocos minutos después del consumo de un alimento con sulfitos. No se ha determinado un umbral por debajo del cual no se produzcan reacciones adversas, y el límite de 10 mg/kg o litro se corresponde con el límite de los métodos de detección de sulfitos disponibles actualmente.</p><p>Se utilizan como conservantes en crustáceos, frutas deshidratadas, productos cárnicos, refrescos, jugos y conservas vegetales, vino, cerveza, vinagre, sidra, salsas de mostaza...</p></div>",
        descripcio_en: "<div class='alergens'><p>The prevalence of sensitivity to sulfites in the population is unknown, but it seems to be rare, except in the asthmatic population. The most frequent adverse reaction is bronchospasm that can occur a few minutes after consuming food with sulfites. There is no threshold below which no adverse reactions occur, and the limit of 10 mg/kg or liter corresponds to the limit of sulfite detection methods currently available.</p><p>They are used as preservatives in crustaceans, dried fruits, meat products, soft drinks, juices and vegetable preserves, wine, beer, vinegar, cider, mustard sauces...</p></div>",
        descripcio_fr: "<div class='alergens'><p>La prévalence de la sensibilité aux sulfites dans la population est inconnue, mais elle semble être rare, sauf dans la population asthmatique. La réaction adverse la plus fréquente est un bronchospasme qui peut survenir quelques minutes après la consommation d'un aliment contenant des sulfites. Il n'y a pas de seuil en dessous duquel aucune réaction adverse ne se produit, et la limite de 10 mg/kg ou litre correspond à la limite des méthodes de détection des sulfites actuellement disponibles.</p><p>Ils sont utilisés comme conservateurs dans les crustacés, les fruits secs, les produits carnés, les boissons gazeuses, les jus et les conserves de légumes, le vin, la bière, le vinaigre, le cidre, les sauces à la moutarde...</p></div>",
        imatge: "al-12.png"
    },
    {
        id: 13,
        nom_ca: "Mol·luscs i derivats",
        nom_es: "Moluscos y derivados",
        nom_en: "Molluscs and derivatives",
        nom_fr: "Mollusques et dérivés",
        subNom_ca: "Mol·luscs i productes a base de mol·luscs",
        subNom_es: "Moluscos y productos a base de moluscos",
        subNom_en: "Molluscs and mollusc-based products",
        subNom_fr: "Mollusques et produits à base de mollusques",
        descripcio_ca: "<div class='alergens'><p>La proteïna al·lergògena principal que es troba als mol·luscs (gasteròpodes, bivalves o cefalòpodes) és la tropomiosina, la mateixa que en els crustacis, i són freqüents els casos d’al·lèrgies encreuades entre mol·luscs i crustacis. A més de consumir-se tal qual, s’utilitzen com a ingredients de determinats preparats, així com en alguns productes com el surimi.</p><p>Es poden trobar en cremes, salses, plats preparats, etc.</p></div>",
        descripcio_es: "<div class='alergens'><p>La principal proteína alergénica que se encuentra en los moluscos (gasterópodos, bivalvos o cefalópodos) es la tropomiosina, la misma que en los crustáceos, y son frecuentes los casos de alergias cruzadas entre moluscos y crustáceos. Además de consumirse tal cual, se utilizan como ingredientes de determinados preparados, así como en algunos productos como el surimi.</p><p>Se pueden encontrar en cremas, salsas, platos preparados, etc.</p></div>",
        descripcio_en: "<div class='alergens'><p>The main allergenic protein found in mollusks (gastropods, bivalves or cephalopods) is tropomyosin, the same as in crustaceans, and cross-reactivity between mollusks and crustaceans is common. In addition to being consumed as is, they are used as ingredients in certain preparations, as well as in some products like surimi.</p><p>They can be found in creams, sauces, prepared dishes, etc.</p></div>",
        descripcio_fr: "<div class='alergens'><p>La principale protéine allergénique présente dans les mollusques (gastéropodes, bivalves ou céphalopodes) est la tropomyosine, la même que dans les crustacés, et il est fréquent que des allergies croisées se produisent entre mollusques et crustacés. En plus d'être consommés tels quels, ils sont utilisés comme ingrédients dans certaines préparations, ainsi que dans certains produits tels que le surimi.</p><p>Ils peuvent être trouvés dans des crèmes, des sauces, des plats préparés, etc.</p></div>",
        imatge: "al-13.png"
    },
    {
        id: 14,
        nom_ca: "Tramussos i derivats",
        nom_es: "Tramuces y derivados",
        nom_en: "Lumps and derivatives",
        nom_fr: "Morceaux et dérivés",
        subNom_ca: "Tramussos i productes a base de tramussoss",
        subNom_es: "Tramuces y productos a base de tramuces",
        subNom_en: "Lumps and lumps-based products",
        subNom_fr: "Morceaux et produits à base de morceaux",
        descripcio_ca: "<div class='alergens'><p>Es tracta d’una planta lleguminosa que té més de 450 espècies diferents; s’hi han documentat casos de reaccions al·lèrgiques directes (a vegades greus) i s’ha demostrat el risc de reactivitat encreuada amb els cacauets.</p><p></p><p>Des de fa uns anys la farina de tramussos s’afegeix a la farina de blat per a l’elaboració de productes de pa.</p><p>Es pot trobar en alguns pans, pastissos, pastes, farines...</p></div>",
        descripcio_es: "<div class='alergens'><p>Se trata de una planta leguminosa que tiene más de 450 especies distintas; se han documentado casos de reacciones alérgicas directas (a veces graves) y se ha demostrado el riesgo de reactividad cruzada con los cacahuetes.</p><p>Desde hace unos años la harina de altramuces se añade a la harina de trigo para la elaboración de productos de pan.</p><p>Se puede encontrar en algunos panes, pasteles, pastas, harinas...</p></div>",
        descripcio_en: "<div class='alergens'><p>It is a leguminous plant that has more than 450 different species; cases of direct allergic reactions (sometimes severe) have been documented and the risk of cross-reactivity with peanuts has been demonstrated.</p><p>For some years lupine flour has been added to wheat flour to make bread products.</p><p>It can be found in some breads, cakes, pastas, flours...</p></div>",
        descripcio_fr: "<div class='alergens'><p>C'est une plante légumineuse qui compte plus de 450 espèces différentes ; des cas de réactions allergiques directes (parfois sévères) ont été documentés et le risque de réactivité croisée avec l'arachide a été démontré.</p><p>Depuis quelques années, la farine de lupin est ajoutée à la farine de blé pour fabriquer des produits de panification.</p><p>On le retrouve dans certains pains, gâteaux, pâtes, farines...</p></div>",
        imatge: "al-14.png"
    }
];